### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by BenGardiner** [Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode-STM32-ARM#1]
I think you need to put the license text in a `LICENSE` file in the top-level to comply with github conventions for licensing.

https://help.github.com/articles/adding-a-license-to-a-repository/

Doing so would satisfy the 'Machine Readability' aspect of the CC's *ALM* recommendation

https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license

**Comment by jeremydaily** [comment]
Can do.
