### ISSUE TITLE
Copyright of `main.c` is assigned (incompatibly) to ST Micro

### ISSUE THREAD

**Issue by BenGardiner** [Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode-STM32-ARM#2]
https://github.com/Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Data-Diode-STM32-ARM/blob/c5b273675d3bb0c0fc5f10308ce3028178a4fffb/src/main.c#L40

**Comment by jeremydaily** [comment]
This is ST's code and I need to leave the copyright intact. This section would not fall under the CC license or any other license that I come up with because it is already copyrighted material. Suggestions?

**Comment by BenGardiner** [comment]
Hmmmm. OK.

I suggest starting from scratch for the ELD-side and J1939-side `*.c` source files then.

**Comment by BenGardiner** [comment]
The software doesn't contain anything wrt the patents right? You should be able to license this as MIT or other permissive license like Attribution-ShareAlike https://creativecommons.org/licenses/ and publish that along with the paper.

This would allow you to simply implement the 'requestor list' as hard-coded array and users could rebuild (for now, until a slicker solution is implemented).

NB: CC-BY-SA 4.0 is GPLv3 compatible https://www.fsf.org/blogs/licensing/creative-commons-by-sa-4-0-declared-one-way-compatible-with-gnu-gpl-version-3

**Comment by jeremydaily** [comment]
I'm planning to use an MIT license for file in any new source code for the system. The license in the individual source files should override the repository license, right?

**Comment by BenGardiner** [comment]
Cool. MIT is fine. And yes, licenses _in_ the source files supersede those
in the LICENSE file of the repo. Plus, your README.md states that
explicitly. It's all good.
